#!/bin/bash
set -e

OPTIONS_FILE="/data/options.json"

echo "========================================="
echo "  Reptile Manager Add-on starting..."
echo "========================================="

# ── Read options ──────────────────────────────────────────────────────────────
if [ -f "$OPTIONS_FILE" ]; then
    ADMIN_USER=$(jq -r '.admin_username // "admin"'   "$OPTIONS_FILE")
    ADMIN_PASS=$(jq -r '.admin_password // "admin123"' "$OPTIONS_FILE")
    SECRET_KEY=$(jq -r '.secret_key     // ""'         "$OPTIONS_FILE")
    API_URL=$(   jq -r '.api_url        // ""'         "$OPTIONS_FILE")
else
    echo "WARNING: $OPTIONS_FILE not found, using defaults"
    ADMIN_USER="admin"; ADMIN_PASS="admin123"; SECRET_KEY=""; API_URL=""
fi

# ── Auto-generate persistent secret key ──────────────────────────────────────
if [ -z "$SECRET_KEY" ]; then
    SECRET_KEY_FILE="/data/.secret_key"
    if [ ! -f "$SECRET_KEY_FILE" ]; then
        echo "Generating new secret key..."
        tr -dc 'a-f0-9' < /dev/urandom | head -c 64 > "$SECRET_KEY_FILE"
    fi
    SECRET_KEY=$(cat "$SECRET_KEY_FILE")
fi

# ── Directories ───────────────────────────────────────────────────────────────
mkdir -p /data/uploads/animals
mkdir -p /var/www/html

# ── Runtime API config for frontend ──────────────────────────────────────────
# This is loaded BEFORE the Vue bundle so frontend can use it
cat > /var/www/html/api-config.js << JSEOF
// Generated by run.sh — do not edit manually
window.__REPTILE_API__ = "${API_URL}";
JSEOF

echo "Admin user  : $ADMIN_USER"
echo "Database    : /data/reptile.db"
echo "Uploads     : /data/uploads"
echo "API URL     : ${API_URL:-'(auto — ingress)'}"
echo "========================================="

# ── Export for supervisord ────────────────────────────────────────────────────
export DATABASE_URL="sqlite:////data/reptile.db"
export UPLOAD_DIR="/data/uploads"
export SECRET_KEY="$SECRET_KEY"
export FIRST_ADMIN_USERNAME="$ADMIN_USER"
export FIRST_ADMIN_PASSWORD="$ADMIN_PASS"

exec supervisord -c /etc/supervisor/conf.d/supervisord.conf
